### ISSUE TITLE
Generating output sequences

### ISSUE THREAD

**Issue by delphinas** [alexarnimueller/LSTM_peptides#3]
Hi. How can I generate the output sequences in fasta or csv files after sampling from trained model?

**Comment by alexarnimueller** [comment]
sorry for the late reply
you can direct the output of the script to a text file in the terminal:

`python LSTM_peptides.py --name testsample --modfile pretrained_model/checkpoint/model_epoch_99.hdf5 --train False --sample 100 >> outputfile.txt
`
